# Generated by Django 4.2.11 on 2024-04-07 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('add', 'Add'), ('edit', 'Edit'), ('delete', 'Delete'), ('put_away', 'Put Away'), ('picking', 'Picking'), ('move', 'Move'), ('status_update', 'Status Update'), ('shelf_update', 'Shelf Update')], max_length=20)),
                ('product_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('shelf', models.CharField(choices=[('A01', 'A01'), ('A02', 'A02'), ('A03', 'A03'), ('B01', 'B01'), ('B02', 'B02'), ('B03', 'B03')], max_length=3, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
                ('nodeMCU_ip', models.CharField(max_length=15)),
            ],
        ),
    ]
